import AutoRefresh from "@/components/AutoRefresh";
import { getBaseUrl } from "@/lib/get-base-url";

interface AirflowDag { dag_id: string; is_active: boolean; is_paused: boolean; description: string | null; owners: string[]; next_dagrun: string | null; }

export default async function PipelinesPage() {
  const res = await fetch(`${getBaseUrl()}/api/airflow/dags`, { cache: "no-store" });
  const body = await res.json();
  if (body.error) return <div className="dashboard-panel border-danger/30 bg-danger-soft p-5 text-sm text-danger">Unable to reach Airflow: {body.error}</div>;
  const dags: AirflowDag[] = body.data ?? [];
  return <div className="flex flex-col gap-8 pb-10"><AutoRefresh intervalMs={60000} /><header><p className="dashboard-eyebrow">Machine learning / orchestration</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Pipeline orchestration</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted">Live DAG status and scheduling telemetry from the Apache Airflow REST API.</p></header><section className="dashboard-panel overflow-hidden"><div className="flex items-center justify-between border-b border-border bg-surface-muted/60 px-5 py-4"><div><h2 className="font-bold">Active DAGs</h2><p className="mt-1 text-xs text-muted">{dags.length} workflows returned</p></div><span className="rounded-md bg-success-soft px-2 py-1 font-mono text-[10px] font-bold text-success">LIVE</span></div><div className="overflow-x-auto"><table className="dashboard-table w-full min-w-[680px] text-left text-sm"><thead><tr><th className="px-5 py-3 font-semibold">DAG ID</th><th className="px-5 py-3 font-semibold">Status</th><th className="px-5 py-3 font-semibold">Owner</th><th className="px-5 py-3 font-semibold">Next run</th></tr></thead><tbody>{dags.length === 0 ? <tr><td colSpan={4} className="px-5 py-10 text-center text-muted">No DAGs found or Airflow is unavailable.</td></tr> : dags.map((dag) => <tr key={dag.dag_id}><td className="px-5 py-4 font-mono text-xs font-semibold">{dag.dag_id}</td><td className="px-5 py-4"><span className={`rounded-md px-2 py-1 font-mono text-[10px] font-bold ${dag.is_paused ? "bg-surface-muted text-muted" : "bg-success-soft text-success"}`}>{dag.is_paused ? "PAUSED" : "ACTIVE"}</span></td><td className="px-5 py-4 text-muted">{dag.owners.join(", ")}</td><td className="px-5 py-4 font-mono text-xs text-muted">{dag.next_dagrun ? new Date(dag.next_dagrun).toLocaleString("id-ID") : "Not scheduled"}</td></tr>)}</tbody></table></div></section></div>;
}
