export default function ArchitectureNarrative() {
  const stages = [
    { n: "01", title: "Data layer", subtitle: "Medallion architecture", accent: "bg-warning", items: ["Bronze · raw", "Silver · clean", "Gold · features"] },
    { n: "02", title: "Orchestrator", subtitle: "Apache Airflow", accent: "bg-danger", items: ["Trigger DAGs", "Task routing", "Error handling"] },
    { n: "03", title: "ML pipeline", subtitle: "Docker-out-of-Docker", accent: "bg-primary", items: ["Train model", "Quality gate", "Persist metrics"] },
    { n: "04", title: "Serving", subtitle: "Next.js UI", accent: "bg-success", items: ["REST API", "Actionable insight", "Dynamic export"] },
  ];
  return <div className="flex flex-col gap-10">
    <div className="flex flex-col gap-6 border-b border-border pb-9 md:flex-row md:items-end md:justify-between"><div className="max-w-3xl"><p className="dashboard-eyebrow">MLOPS COMMAND CENTER / LIVE ENVIRONMENT</p><h1 className="mt-4 text-balance text-4xl font-semibold tracking-[-0.04em] text-foreground md:text-6xl">Operational intelligence<br /><span className="text-muted">for machine learning.</span></h1><p className="mt-5 max-w-xl text-sm leading-6 text-muted">End-to-end machine learning operations with automated training, quality gates, and business-ready outputs.</p></div><div className="flex shrink-0 items-center gap-3 rounded-full border border-success/25 bg-success-soft px-4 py-2.5 text-xs font-semibold text-success"><span className="size-2 rounded-full bg-success" />Live environment</div></div>
    <div className="dashboard-panel relative overflow-hidden p-6 md:p-8"><div className="absolute right-0 top-0 size-56 rounded-full bg-primary/10 blur-3xl" /><div className="relative flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div className="max-w-3xl text-sm leading-6 text-muted"><p><strong className="text-foreground">Executive summary.</strong> This production-scale MLOps ecosystem moves raw data from Bronze to Gold, detects changes, triggers isolated continuous training, evaluates candidates through strict quality gates, and publishes actionable insights in near real time.</p></div><div className="flex flex-wrap gap-2 font-mono text-[10px] font-semibold text-muted"><span className="rounded-full border border-primary/30 bg-primary-soft px-3 py-1.5 text-primary">NEXT.JS 16</span><span className="rounded-full border border-border bg-surface-muted px-3 py-1.5">AIRFLOW</span><span className="rounded-full border border-border bg-surface-muted px-3 py-1.5">POSTGRESQL</span></div></div></div>
    <div className="flex flex-col gap-5"><div><p className="dashboard-eyebrow">Pipeline architecture</p><h2 className="mt-2 text-xl font-semibold tracking-tight text-foreground">From source data to decision surface</h2></div><div className="grid grid-cols-1 gap-px overflow-hidden rounded-lg border border-border bg-border md:grid-cols-2 xl:grid-cols-4">{stages.map((stage) => <div key={stage.n} className="group relative bg-surface p-6 transition-colors hover:bg-surface-muted"><div className={`mb-8 flex size-9 items-center justify-center rounded-md ${stage.accent} text-xs font-bold text-background`}>{stage.n}</div><h3 className="font-semibold text-foreground">{stage.title}</h3><p className="mt-1 font-mono text-[10px] uppercase tracking-wide text-muted">{stage.subtitle}</p><ul className="mt-5 flex flex-col gap-2 text-xs text-muted">{stage.items.map((item) => <li key={item} className="flex items-center gap-2"><span className="size-1 rounded-full bg-border-strong" />{item}</li>)}</ul></div>)}</div></div>
  </div>;
}
