name: "gold_layer_models"
version: "1.0.0"

profile: "gold_layer_models"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  gold_layer_models:
    example:
      +materialized: table
