DROP SCHEMA IF EXISTS operational_raw CASCADE;
DROP SCHEMA IF EXISTS operational CASCADE;
DROP SCHEMA IF EXISTS silver CASCADE;
DROP SCHEMA IF EXISTS gold CASCADE;

CREATE SCHEMA operational_raw;
CREATE SCHEMA operational;
CREATE SCHEMA silver;
CREATE SCHEMA gold;